### ISSUE TITLE
Weird metamask caching

### ISSUE THREAD

**Issue by Philmod** [chainskills/chainlist#5]
When you restart your local node, metamask caches the old contract and its data.

You have to switch metamask network to any other network then back to the local node to see changes.

**Comment by sarbogast** [comment]
Yes, unfortunately, it's independent of our will. Metamask does that sort of things, they even documented it in their FAQ but I can't find it anymore.

**Comment by Philmod** [comment]
I meant you could document this in your repo to make it clear for future
developers.

**Comment by sarbogast** [comment]
Good point. I added it to the README file. Thanks.
